#ifndef FLEXPRET_CONFIG_H
#define FLEXPRET_CONFIG_H

#ifndef FLEXPRET_HW_THREADS_NUMS
#define FLEXPRET_HW_THREADS_NUMS 8
#endif

#define FLEXPRET_MAX_HW_THREADS_NUMS 8

#ifndef FLEXPRET_ISPM_SIZE
#define FLEXPRET_ISPM_SIZE 64
#endif

#ifndef FLEXPRET_DSPM_SIZE
#define FLEXPRET_DSPM_SIZE 64
#endif

#ifndef FLEXPRET_MUTEX_MAX_NUM
#define FLEXPRET_MUTEX_MAX_NUM 8
#endif

#ifndef FLEXPRET_FREQ
#define FLEXPRET_FREQ 100000000 // 100Mhz
#endif

#ifndef FLEXPRET_WAIT_PERIOD
#define FLEXPRET_WAIT_PERIOD 10000 // 10000 cycle
#endif

#endif